inc:
  # Blog Information
  title:        "Superion Airlines"
  subtitle:     "The only Airline in the Pacific that consistantly battles Bots!"
  cover_image:  artdeco_plane.png
  logo:         logo-wide.png
  
  # Company information
  company:      Superion Air
  url:          https://SuperionAir.co/
  twitter:      SuperionAir
  gplus:        '105099525398001894569'
  about_link:   https://SuperionAir.co/about/
  
  # Test 
  testing: 
  - url: http://www.distilnetworks.com/
    text:      "Distil Networks"
  - url: http://www.f5.com
    text:	"F5 Networks"
  - url: http://www.imperva.com
    text:	"Imperva"
  
  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  superionair
  figures:
    dir: /figures
    enumerate: true
    analytics: true
 
  # Sharing settings
  sharing:
    twitter:    true
    facebook:   false
    gplus:      false
    hn:         false
    
  
 # Analytics     
  analytics:
    google: true
      
      
  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'
  
  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

url:         https://SuperionAir.co
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    pdt

# Show future posts
future:      true
show_drafts: true
limit_posts: 0
highligher:    true

relative_permalinks: true

permalink:     pretty
paginate_path: 'page:num'
paginate: 10

markdown:      redcarpet
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        81
baseurl:     /
lsi:         false
gems:	[jekyll-assets, jekyll_figure]
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: [smart, no_intra_emphasis, tables, strikethrough, lax_spacing, superscript]

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true
#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:

  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: true
