source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll_figure'
gem 'maruku'
gem 'rake'
gem 'sass'
gem 'uglifier'
gem 'github-pages'
gem 'therubyracer'
gem 'neat'
gem 'compass'
gem 'bootstrap-sass'
